version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: atm_user
      POSTGRES_PASSWORD: atm_pass
      POSTGRES_DB: atm_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://atm_user:atm_pass@db:5432/atm_db
    volumes:
      - ./:/app
    tty: true
volumes:
  db_data:
